### ISSUE TITLE
Bug with tuple-specified linestyles

### ISSUE THREAD

**Issue by MBravoS** [MBravoS/splotch#17]
`base_funcs.dict_splicer()` breaks when it receives a tuple specifying the linestyle of a plot. We should add a test for data type when _linestyle_ is given as a key in plot_par, and ensure that it gets passed correctly (wrapping it in a list works fine).

**Comment by AstroRobin** [comment]
This also has further-reaching implications for any color being given as a tuple (e.g. (r,g,b,a)).
To fix this, we can check the first element of any tuple given to dict_splicer() if it is purely a `'string'` OR the first element is explicitly numeric, then it should be treated as a single value rather than a set of values for multiple lines.

**Comment by MBravoS** [comment]
Solve as of version 0.4.1.2.
