### ISSUE TITLE
Parsing multidimensional arrays into splotch.scatter()

### ISSUE THREAD

**Issue by AstroRobin** [MBravoS/splotch#37]
The current functionality in `scatter()` is that if `xdata` is not a list OR has only one dimension, it should wrapped by a list to then be iterated over. This currently works by the following:
```
if type(xdata) is list or len(shape(xdata))==1:
    xdata = [xdata]
```

This, however, does not work if the size of the sublists in `xdata` are not equal in size as this passes as now a 1 dimensional list.

**Comment by MBravoS** [comment]
This seems to happen because np.shape() seems to internally convert array-likes into ndarrays, which if they are constructed from list with sub-lists of different length returns an array wrapping the list. This can be spotted as the dtype of such an array is `dtype('O')`, so as of 0.5.1.0 I have modified the check to be `if type(xdata) is not list or (len(shape(xdata))==1 and array(x).dtype is not dtype('O')):`. In theory this could produce issues if the data set is meant to be a ndarray of `dtype('O')`, but I can't see the use case of that in this function. A similar issue affected `plots_1d.hist()`, the same fix is in place since 0.5.1.0.
